1.	Python program to add two Matrices

In [1]:
# Program to add two matrices
# using zip()

X = [[1,2,3],
	[4 ,5,6],
	[7 ,8,9]]

Y = [[9,8,7],
	[6,5,4],
	[3,2,1]]

result = [map(sum, zip(*t)) for t in zip(X, Y)]

print(result)


[<map object at 0x000002307082E4F0>, <map object at 0x000002307086E0A0>, <map object at 0x000002307086E130>]


2.	Python program to multiply two matrices

In [2]:
# Program to multiply two matrices using nested loops

# take a 3x3 matrix
A = [[12, 7, 3],
	[4, 5, 6],
	[7, 8, 9]]

# take a 3x4 matrix
B = [[5, 8, 1, 2],
	[6, 7, 3, 0],
	[4, 5, 9, 1]]
	
result = [[0, 0, 0, 0],
		[0, 0, 0, 0],
		[0, 0, 0, 0]]

# iterating by row of A
for i in range(len(A)):

	# iterating by column by B
	for j in range(len(B[0])):

		# iterating by rows of B
		for k in range(len(B)):
			result[i][j] += A[i][k] * B[k][j]

for r in result:
	print(r)


[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


3.	Python program for Matrix Product

In [3]:
def Multiply(A,B):
    result=[ [0,0,0],[0,0,0],[0,0,0] ]
    #for rows
    for i in range(len(A)):
        #for columns
        for j in range(len(B[0])):
            #for rows of matrix B
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]

    for p in result:
        print(p)
    return 0

A = [ [1, 2, 3],[6, 7, 4], [8, 10, 11] ]
B = [[1, 5, 3],[2, 6, 5], [7, 4, 9] ]

print("Result: ")
Multiply(A,B)

Result: 
[26, 29, 40]
[48, 88, 89]
[105, 144, 173]


0

4.	Adding and Subtracting Matrices in Python

In [4]:
# importing numpy as np
import numpy as np


# creating first matrix
A = np.array([[1, 2], [3, 4]])

# creating second matrix
B = np.array([[4, 5], [6, 7]])

print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)

# adding two matrix
print("Addition of two matrix")
print(np.add(A, B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Addition of two matrix
[[ 5  7]
 [ 9 11]]


5.	Transpose a matrix in Single line in Python

In [5]:
# You need to install numpy in order to import it
import numpy as np
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)
print("\n")
print(matrix.T)


[[1 2 3]
 [4 5 6]]


[[1 4]
 [2 5]
 [3 6]]


6.	Python | Matrix creation of n*n

In [6]:
# Python3 code to demonstrate
# matrix creation of n * n
# using next() + itertools.count()
import itertools

# initializing N
N = 4

# printing dimension
print("The dimension : " + str(N))

# using next() + itertools.count()
# matrix creation of n * n
temp = itertools.count(1)
res = [[next(temp) for i in range(N)] for i in range(N)]

# print result
print("The created matrix of N * N: " + str(res))


The dimension : 4
The created matrix of N * N: [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]


7.	Python | Get Kth Column of Matrix

In [7]:
# Python3 code to demonstrate working of
# Get Kth Column of Matrix
# using list comprehension

# initialize list
test_list = [[4, 5, 6], [8, 1, 10], [7, 12, 5]]

# printing original list
print("The original list is : " + str(test_list))

# initialize K
K = 2

# Get Kth Column of Matrix
# using list comprehension
res = [sub[K] for sub in test_list]

# printing result
print("The Kth column of matrix is : " + str(res))


The original list is : [[4, 5, 6], [8, 1, 10], [7, 12, 5]]
The Kth column of matrix is : [6, 10, 5]


8.	Python – Vertical Concatenation in Matrix

In [8]:
# Python3 code to demonstrate working of
# Vertical Concatenation in Matrix
# Using loop

# initializing lists
test_list = [["Gfg", "good"], ["is", "for"], ["Best"]]

# printing original list
print("The original list : " + str(test_list))

# using loop for iteration
res = []
N = 0
while N != len(test_list):
	temp = ''
	for idx in test_list:
		
		# checking for valid index / column
		try: temp = temp + idx[N]
		except IndexError: pass
	res.append(temp)
	N = N + 1

res = [ele for ele in res if ele]

# printing result
print("List after column Concatenation : " + str(res))


The original list : [['Gfg', 'good'], ['is', 'for'], ['Best']]
List after column Concatenation : ['GfgisBest', 'goodfor']


9.	Python program to check if a string is palindrome or not

In [9]:
# function which return reverse of a string

def isPalindrome(s):
	return s == s[::-1]


# Driver code
s = "malayalam"
ans = isPalindrome(s)

if ans:
	print("Yes")
else:
	print("No")


Yes


10.	Python program to check whether the string is Symmetrical or Palindrome

In [10]:
string = 'amaama'
half = int(len(string) / 2)

if len(string) % 2 == 0: # even
	first_str = string[:half]
	second_str = string[half:]
else: # odd
	first_str = string[:half]
	second_str = string[half+1:]

# symmetric
if first_str == second_str:
	print(string, 'string is symmertical')
else:
	print(string, 'string is not symmertical')

# palindrome
if first_str == second_str[::-1]: # ''.join(reversed(second_str)) [slower]
	print(string, 'string is palindrome')
else:
	print(string, 'string is not palindrome')


amaama string is symmertical
amaama string is palindrome
